[package]
name = "sea-extra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.39", features = ["time"] }
async-trait = "0.1"
sea-orm = "0.12"
futures = "0.3"
